#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include "fastkv.h"

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 28), // char const *()(fastkv_err_t)
/*  1 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // fastkv_err_t
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_cursor_t *)
/*  4 */ _CFFI_OP(_CFFI_OP_POINTER, 126), // fastkv_cursor_t *
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_cursor_t *, fastkv_slice_t *)
/*  7 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/*  8 */ _CFFI_OP(_CFFI_OP_POINTER, 12), // fastkv_slice_t *
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_cursor_t *, fastkv_slice_t)
/* 11 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 12 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // fastkv_slice_t
/* 13 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 14 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_db_t * *, fastkv_opts_t const *)
/* 15 */ _CFFI_OP(_CFFI_OP_POINTER, 19), // fastkv_db_t * *
/* 16 */ _CFFI_OP(_CFFI_OP_POINTER, 129), // fastkv_opts_t const *
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_db_t *)
/* 19 */ _CFFI_OP(_CFFI_OP_POINTER, 127), // fastkv_db_t *
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_db_t *, _Bool, fastkv_txn_t * *)
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 23 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 24 */ _CFFI_OP(_CFFI_OP_POINTER, 85), // fastkv_txn_t * *
/* 25 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_db_t *, char const *)
/* 27 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 28 */ _CFFI_OP(_CFFI_OP_POINTER, 125), // char const *
/* 29 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 30 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_db_t *, char const *, char const *, fastkv_index_t * *)
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 32 */ _CFFI_OP(_CFFI_OP_NOOP, 28),
/* 33 */ _CFFI_OP(_CFFI_OP_NOOP, 28),
/* 34 */ _CFFI_OP(_CFFI_OP_POINTER, 68), // fastkv_index_t * *
/* 35 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 36 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_db_t *, char const *, int(*)(fastkv_slice_t, fastkv_slice_t, fastkv_slice_t *, void *), void *, fastkv_index_t * *)
/* 37 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 38 */ _CFFI_OP(_CFFI_OP_NOOP, 28),
/* 39 */ _CFFI_OP(_CFFI_OP_POINTER, 106), // int(*)(fastkv_slice_t, fastkv_slice_t, fastkv_slice_t *, void *)
/* 40 */ _CFFI_OP(_CFFI_OP_POINTER, 137), // void *
/* 41 */ _CFFI_OP(_CFFI_OP_NOOP, 34),
/* 42 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 43 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_db_t *, fastkv_slice_t)
/* 44 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 45 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 46 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 47 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_db_t *, fastkv_slice_t, fastkv_slice_t *)
/* 48 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 49 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 50 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 51 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 52 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_db_t *, fastkv_slice_t, fastkv_slice_t)
/* 53 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 54 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 55 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 56 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 57 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_db_t *, fastkv_slice_t, fastkv_slice_t, uint64_t)
/* 58 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 59 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 60 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 61 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24), // uint64_t
/* 62 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 63 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_db_t *, fastkv_stats_t *)
/* 64 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 65 */ _CFFI_OP(_CFFI_OP_POINTER, 130), // fastkv_stats_t *
/* 66 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 67 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_index_t *, fastkv_slice_t, fastkv_err_t(*)(fastkv_slice_t, void *), void *)
/* 68 */ _CFFI_OP(_CFFI_OP_POINTER, 128), // fastkv_index_t *
/* 69 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 70 */ _CFFI_OP(_CFFI_OP_POINTER, 80), // fastkv_err_t(*)(fastkv_slice_t, void *)
/* 71 */ _CFFI_OP(_CFFI_OP_NOOP, 40),
/* 72 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 73 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_index_t *, fastkv_slice_t, fastkv_slice_t, fastkv_err_t(*)(fastkv_slice_t, void *), void *)
/* 74 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 75 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 76 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 77 */ _CFFI_OP(_CFFI_OP_NOOP, 70),
/* 78 */ _CFFI_OP(_CFFI_OP_NOOP, 40),
/* 79 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 80 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_slice_t, void *)
/* 81 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 82 */ _CFFI_OP(_CFFI_OP_NOOP, 40),
/* 83 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 84 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_txn_t *)
/* 85 */ _CFFI_OP(_CFFI_OP_POINTER, 131), // fastkv_txn_t *
/* 86 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 87 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_txn_t *, fastkv_cursor_dir_t, fastkv_cursor_t * *)
/* 88 */ _CFFI_OP(_CFFI_OP_NOOP, 85),
/* 89 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // fastkv_cursor_dir_t
/* 90 */ _CFFI_OP(_CFFI_OP_POINTER, 4), // fastkv_cursor_t * *
/* 91 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 92 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_txn_t *, fastkv_slice_t)
/* 93 */ _CFFI_OP(_CFFI_OP_NOOP, 85),
/* 94 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 95 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 96 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_txn_t *, fastkv_slice_t, fastkv_slice_t *)
/* 97 */ _CFFI_OP(_CFFI_OP_NOOP, 85),
/* 98 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 99 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 100 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 101 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // fastkv_err_t()(fastkv_txn_t *, fastkv_slice_t, fastkv_slice_t)
/* 102 */ _CFFI_OP(_CFFI_OP_NOOP, 85),
/* 103 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 104 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 105 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 106 */ _CFFI_OP(_CFFI_OP_FUNCTION, 132), // int()(fastkv_slice_t, fastkv_slice_t, fastkv_slice_t *, void *)
/* 107 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 108 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 109 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 110 */ _CFFI_OP(_CFFI_OP_NOOP, 40),
/* 111 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 112 */ _CFFI_OP(_CFFI_OP_FUNCTION, 40), // void *()(size_t)
/* 113 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28), // size_t
/* 114 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 115 */ _CFFI_OP(_CFFI_OP_FUNCTION, 137), // void()(fastkv_cursor_t *)
/* 116 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 117 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 118 */ _CFFI_OP(_CFFI_OP_FUNCTION, 137), // void()(fastkv_db_t *, fastkv_slice_t *)
/* 119 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 120 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 121 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 122 */ _CFFI_OP(_CFFI_OP_FUNCTION, 137), // void()(void *)
/* 123 */ _CFFI_OP(_CFFI_OP_NOOP, 40),
/* 124 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 125 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 126 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // fastkv_cursor_t
/* 127 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // fastkv_db_t
/* 128 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // fastkv_index_t
/* 129 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // fastkv_opts_t
/* 130 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // fastkv_stats_t
/* 131 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 6), // fastkv_txn_t
/* 132 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 133 */ _CFFI_OP(_CFFI_OP_POINTER, 134), // uint8_t const *
/* 134 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 135 */ _CFFI_OP(_CFFI_OP_POINTER, 112), // void *(*)(size_t)
/* 136 */ _CFFI_OP(_CFFI_OP_POINTER, 122), // void(*)(void *)
/* 137 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_FASTKV_CURSOR_FORWARD(unsigned long long *o)
{
  int n = (FASTKV_CURSOR_FORWARD) <= 0;
  *o = (unsigned long long)((FASTKV_CURSOR_FORWARD) | 0);  /* check that FASTKV_CURSOR_FORWARD is an integer */
  return n;
}

static int _cffi_const_FASTKV_CURSOR_BACKWARD(unsigned long long *o)
{
  int n = (FASTKV_CURSOR_BACKWARD) <= 0;
  *o = (unsigned long long)((FASTKV_CURSOR_BACKWARD) | 0);  /* check that FASTKV_CURSOR_BACKWARD is an integer */
  return n;
}

static int _cffi_const_FASTKV_OK(unsigned long long *o)
{
  int n = (FASTKV_OK) <= 0;
  *o = (unsigned long long)((FASTKV_OK) | 0);  /* check that FASTKV_OK is an integer */
  return n;
}

static int _cffi_const_FASTKV_ERR_NOMEM(unsigned long long *o)
{
  int n = (FASTKV_ERR_NOMEM) <= 0;
  *o = (unsigned long long)((FASTKV_ERR_NOMEM) | 0);  /* check that FASTKV_ERR_NOMEM is an integer */
  return n;
}

static int _cffi_const_FASTKV_ERR_INVAL(unsigned long long *o)
{
  int n = (FASTKV_ERR_INVAL) <= 0;
  *o = (unsigned long long)((FASTKV_ERR_INVAL) | 0);  /* check that FASTKV_ERR_INVAL is an integer */
  return n;
}

static int _cffi_const_FASTKV_ERR_IO(unsigned long long *o)
{
  int n = (FASTKV_ERR_IO) <= 0;
  *o = (unsigned long long)((FASTKV_ERR_IO) | 0);  /* check that FASTKV_ERR_IO is an integer */
  return n;
}

static int _cffi_const_FASTKV_ERR_CORRUPT(unsigned long long *o)
{
  int n = (FASTKV_ERR_CORRUPT) <= 0;
  *o = (unsigned long long)((FASTKV_ERR_CORRUPT) | 0);  /* check that FASTKV_ERR_CORRUPT is an integer */
  return n;
}

static int _cffi_const_FASTKV_ERR_FULL(unsigned long long *o)
{
  int n = (FASTKV_ERR_FULL) <= 0;
  *o = (unsigned long long)((FASTKV_ERR_FULL) | 0);  /* check that FASTKV_ERR_FULL is an integer */
  return n;
}

static int _cffi_const_FASTKV_ERR_NOTFOUND(unsigned long long *o)
{
  int n = (FASTKV_ERR_NOTFOUND) <= 0;
  *o = (unsigned long long)((FASTKV_ERR_NOTFOUND) | 0);  /* check that FASTKV_ERR_NOTFOUND is an integer */
  return n;
}

static int _cffi_const_FASTKV_ERR_KEYSIZE(unsigned long long *o)
{
  int n = (FASTKV_ERR_KEYSIZE) <= 0;
  *o = (unsigned long long)((FASTKV_ERR_KEYSIZE) | 0);  /* check that FASTKV_ERR_KEYSIZE is an integer */
  return n;
}

static int _cffi_const_FASTKV_ERR_VALSIZE(unsigned long long *o)
{
  int n = (FASTKV_ERR_VALSIZE) <= 0;
  *o = (unsigned long long)((FASTKV_ERR_VALSIZE) | 0);  /* check that FASTKV_ERR_VALSIZE is an integer */
  return n;
}

static int _cffi_const_FASTKV_ERR_TXN_RO(unsigned long long *o)
{
  int n = (FASTKV_ERR_TXN_RO) <= 0;
  *o = (unsigned long long)((FASTKV_ERR_TXN_RO) | 0);  /* check that FASTKV_ERR_TXN_RO is an integer */
  return n;
}

static int _cffi_const_FASTKV_ERR_TXN_CONFLICT(unsigned long long *o)
{
  int n = (FASTKV_ERR_TXN_CONFLICT) <= 0;
  *o = (unsigned long long)((FASTKV_ERR_TXN_CONFLICT) | 0);  /* check that FASTKV_ERR_TXN_CONFLICT is an integer */
  return n;
}

static int _cffi_const_FASTKV_ERR_TXN_CLOSED(unsigned long long *o)
{
  int n = (FASTKV_ERR_TXN_CLOSED) <= 0;
  *o = (unsigned long long)((FASTKV_ERR_TXN_CLOSED) | 0);  /* check that FASTKV_ERR_TXN_CLOSED is an integer */
  return n;
}

static int _cffi_const_FASTKV_ERR_CURSOR_EOF(unsigned long long *o)
{
  int n = (FASTKV_ERR_CURSOR_EOF) <= 0;
  *o = (unsigned long long)((FASTKV_ERR_CURSOR_EOF) | 0);  /* check that FASTKV_ERR_CURSOR_EOF is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_fastkv_opts_t(fastkv_opts_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->path; (void)tmp; }
  (void)((p->map_size) | 0);  /* check that 'fastkv_opts_t.map_size' is an integer */
  (void)((p->arena_size) | 0);  /* check that 'fastkv_opts_t.arena_size' is an integer */
  (void)((p->sync_writes) | 0);  /* check that 'fastkv_opts_t.sync_writes' is an integer */
  (void)((p->read_only) | 0);  /* check that 'fastkv_opts_t.read_only' is an integer */
  { void *(* *tmp)(size_t) = &p->malloc_fn; (void)tmp; }
  { void(* *tmp)(void *) = &p->free_fn; (void)tmp; }
}
struct _cffi_align_typedef_fastkv_opts_t { char x; fastkv_opts_t y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_fastkv_slice_t(fastkv_slice_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { uint8_t const * *tmp = &p->data; (void)tmp; }
  (void)((p->len) | 0);  /* check that 'fastkv_slice_t.len' is an integer */
}
struct _cffi_align_typedef_fastkv_slice_t { char x; fastkv_slice_t y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_fastkv_stats_t(fastkv_stats_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->num_keys) | 0);  /* check that 'fastkv_stats_t.num_keys' is an integer */
  (void)((p->num_txn_committed) | 0);  /* check that 'fastkv_stats_t.num_txn_committed' is an integer */
  (void)((p->num_txn_aborted) | 0);  /* check that 'fastkv_stats_t.num_txn_aborted' is an integer */
  (void)((p->num_txn_conflicts) | 0);  /* check that 'fastkv_stats_t.num_txn_conflicts' is an integer */
  (void)((p->wal_bytes_written) | 0);  /* check that 'fastkv_stats_t.wal_bytes_written' is an integer */
  (void)((p->snapshot_count) | 0);  /* check that 'fastkv_stats_t.snapshot_count' is an integer */
  (void)((p->arena_alloc_bytes) | 0);  /* check that 'fastkv_stats_t.arena_alloc_bytes' is an integer */
}
struct _cffi_align_typedef_fastkv_stats_t { char x; fastkv_stats_t y; };

static fastkv_err_t _cffi_d_fastkv_close(fastkv_db_t * x0)
{
  return fastkv_close(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_close(PyObject *self, PyObject *arg0)
{
  fastkv_db_t * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_close(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_close _cffi_d_fastkv_close
#endif

static void _cffi_d_fastkv_cursor_close(fastkv_cursor_t * x0)
{
  fastkv_cursor_close(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_cursor_close(PyObject *self, PyObject *arg0)
{
  fastkv_cursor_t * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_cursor_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { fastkv_cursor_close(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_fastkv_cursor_close _cffi_d_fastkv_cursor_close
#endif

static fastkv_err_t _cffi_d_fastkv_cursor_key(fastkv_cursor_t * x0, fastkv_slice_t * x1)
{
  return fastkv_cursor_key(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_cursor_key(PyObject *self, PyObject *args)
{
  fastkv_cursor_t * x0;
  fastkv_slice_t * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "fastkv_cursor_key", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_cursor_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (fastkv_slice_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(8), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_cursor_key(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_cursor_key _cffi_d_fastkv_cursor_key
#endif

static fastkv_err_t _cffi_d_fastkv_cursor_next(fastkv_cursor_t * x0)
{
  return fastkv_cursor_next(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_cursor_next(PyObject *self, PyObject *arg0)
{
  fastkv_cursor_t * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_cursor_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_cursor_next(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_cursor_next _cffi_d_fastkv_cursor_next
#endif

static fastkv_err_t _cffi_d_fastkv_cursor_open(fastkv_txn_t * x0, fastkv_cursor_dir_t x1, fastkv_cursor_t * * x2)
{
  return fastkv_cursor_open(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_cursor_open(PyObject *self, PyObject *args)
{
  fastkv_txn_t * x0;
  fastkv_cursor_dir_t x1;
  fastkv_cursor_t * * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "fastkv_cursor_open", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(85), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_txn_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(85), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(89), arg1) < 0)
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(90), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (fastkv_cursor_t * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(90), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_cursor_open(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_cursor_open _cffi_d_fastkv_cursor_open
#endif

static fastkv_err_t _cffi_d_fastkv_cursor_seek(fastkv_cursor_t * x0, fastkv_slice_t x1)
{
  return fastkv_cursor_seek(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_cursor_seek(PyObject *self, PyObject *args)
{
  fastkv_cursor_t * x0;
  fastkv_slice_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "fastkv_cursor_seek", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_cursor_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(12), arg1) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_cursor_seek(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static fastkv_err_t _cffi_f_fastkv_cursor_seek(fastkv_cursor_t * x0, fastkv_slice_t *x1)
{
  fastkv_err_t result;
  { result = fastkv_cursor_seek(x0, *x1); }
  return result;
}
#endif

static fastkv_err_t _cffi_d_fastkv_cursor_value(fastkv_cursor_t * x0, fastkv_slice_t * x1)
{
  return fastkv_cursor_value(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_cursor_value(PyObject *self, PyObject *args)
{
  fastkv_cursor_t * x0;
  fastkv_slice_t * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "fastkv_cursor_value", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_cursor_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (fastkv_slice_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(8), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_cursor_value(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_cursor_value _cffi_d_fastkv_cursor_value
#endif

static fastkv_err_t _cffi_d_fastkv_delete(fastkv_db_t * x0, fastkv_slice_t x1)
{
  return fastkv_delete(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_delete(PyObject *self, PyObject *args)
{
  fastkv_db_t * x0;
  fastkv_slice_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "fastkv_delete", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(12), arg1) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_delete(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static fastkv_err_t _cffi_f_fastkv_delete(fastkv_db_t * x0, fastkv_slice_t *x1)
{
  fastkv_err_t result;
  { result = fastkv_delete(x0, *x1); }
  return result;
}
#endif

static void _cffi_d_fastkv_free_value(fastkv_db_t * x0, fastkv_slice_t * x1)
{
  fastkv_free_value(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_free_value(PyObject *self, PyObject *args)
{
  fastkv_db_t * x0;
  fastkv_slice_t * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "fastkv_free_value", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (fastkv_slice_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(8), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { fastkv_free_value(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_fastkv_free_value _cffi_d_fastkv_free_value
#endif

static fastkv_err_t _cffi_d_fastkv_get(fastkv_db_t * x0, fastkv_slice_t x1, fastkv_slice_t * x2)
{
  return fastkv_get(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_get(PyObject *self, PyObject *args)
{
  fastkv_db_t * x0;
  fastkv_slice_t x1;
  fastkv_slice_t * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "fastkv_get", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(12), arg1) < 0)
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (fastkv_slice_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(8), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_get(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static fastkv_err_t _cffi_f_fastkv_get(fastkv_db_t * x0, fastkv_slice_t *x1, fastkv_slice_t * x2)
{
  fastkv_err_t result;
  { result = fastkv_get(x0, *x1, x2); }
  return result;
}
#endif

static fastkv_err_t _cffi_d_fastkv_index_create(fastkv_db_t * x0, char const * x1, int(* x2)(fastkv_slice_t, fastkv_slice_t, fastkv_slice_t *, void *), void * x3, fastkv_index_t * * x4)
{
  return fastkv_index_create(x0, x1, x2, x3, x4);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_index_create(PyObject *self, PyObject *args)
{
  fastkv_db_t * x0;
  char const * x1;
  int(* x2)(fastkv_slice_t, fastkv_slice_t, fastkv_slice_t *, void *);
  void * x3;
  fastkv_index_t * * x4;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;

  if (!PyArg_UnpackTuple(args, "fastkv_index_create", 5, 5, &arg0, &arg1, &arg2, &arg3, &arg4))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(28), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x2 = (int(*)(fastkv_slice_t, fastkv_slice_t, fastkv_slice_t *, void *))_cffi_to_c_pointer(arg2, _cffi_type(39));
  if (x2 == (int(*)(fastkv_slice_t, fastkv_slice_t, fastkv_slice_t *, void *))NULL && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(40), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (void *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(40), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(34), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (fastkv_index_t * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(34), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_index_create(x0, x1, x2, x3, x4); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_index_create _cffi_d_fastkv_index_create
#endif

static fastkv_err_t _cffi_d_fastkv_index_drop(fastkv_db_t * x0, char const * x1)
{
  return fastkv_index_drop(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_index_drop(PyObject *self, PyObject *args)
{
  fastkv_db_t * x0;
  char const * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "fastkv_index_drop", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(28), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_index_drop(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_index_drop _cffi_d_fastkv_index_drop
#endif

static fastkv_err_t _cffi_d_fastkv_index_lookup(fastkv_index_t * x0, fastkv_slice_t x1, fastkv_err_t(* x2)(fastkv_slice_t, void *), void * x3)
{
  return fastkv_index_lookup(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_index_lookup(PyObject *self, PyObject *args)
{
  fastkv_index_t * x0;
  fastkv_slice_t x1;
  fastkv_err_t(* x2)(fastkv_slice_t, void *);
  void * x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "fastkv_index_lookup", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_index_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(68), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(12), arg1) < 0)
    return NULL;

  x2 = (fastkv_err_t(*)(fastkv_slice_t, void *))_cffi_to_c_pointer(arg2, _cffi_type(70));
  if (x2 == (fastkv_err_t(*)(fastkv_slice_t, void *))NULL && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(40), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (void *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(40), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_index_lookup(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static fastkv_err_t _cffi_f_fastkv_index_lookup(fastkv_index_t * x0, fastkv_slice_t *x1, fastkv_err_t(* x2)(fastkv_slice_t, void *), void * x3)
{
  fastkv_err_t result;
  { result = fastkv_index_lookup(x0, *x1, x2, x3); }
  return result;
}
#endif

static fastkv_err_t _cffi_d_fastkv_index_range(fastkv_index_t * x0, fastkv_slice_t x1, fastkv_slice_t x2, fastkv_err_t(* x3)(fastkv_slice_t, void *), void * x4)
{
  return fastkv_index_range(x0, x1, x2, x3, x4);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_index_range(PyObject *self, PyObject *args)
{
  fastkv_index_t * x0;
  fastkv_slice_t x1;
  fastkv_slice_t x2;
  fastkv_err_t(* x3)(fastkv_slice_t, void *);
  void * x4;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;

  if (!PyArg_UnpackTuple(args, "fastkv_index_range", 5, 5, &arg0, &arg1, &arg2, &arg3, &arg4))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_index_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(68), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(12), arg1) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x2, _cffi_type(12), arg2) < 0)
    return NULL;

  x3 = (fastkv_err_t(*)(fastkv_slice_t, void *))_cffi_to_c_pointer(arg3, _cffi_type(70));
  if (x3 == (fastkv_err_t(*)(fastkv_slice_t, void *))NULL && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(40), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (void *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(40), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_index_range(x0, x1, x2, x3, x4); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static fastkv_err_t _cffi_f_fastkv_index_range(fastkv_index_t * x0, fastkv_slice_t *x1, fastkv_slice_t *x2, fastkv_err_t(* x3)(fastkv_slice_t, void *), void * x4)
{
  fastkv_err_t result;
  { result = fastkv_index_range(x0, *x1, *x2, x3, x4); }
  return result;
}
#endif

static fastkv_err_t _cffi_d_fastkv_json_index_create(fastkv_db_t * x0, char const * x1, char const * x2, fastkv_index_t * * x3)
{
  return fastkv_json_index_create(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_json_index_create(PyObject *self, PyObject *args)
{
  fastkv_db_t * x0;
  char const * x1;
  char const * x2;
  fastkv_index_t * * x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "fastkv_json_index_create", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(28), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(28), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(34), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (fastkv_index_t * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(34), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_json_index_create(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_json_index_create _cffi_d_fastkv_json_index_create
#endif

static fastkv_err_t _cffi_d_fastkv_open(fastkv_db_t * * x0, fastkv_opts_t const * x1)
{
  return fastkv_open(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_open(PyObject *self, PyObject *args)
{
  fastkv_db_t * * x0;
  fastkv_opts_t const * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "fastkv_open", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(15), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(16), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (fastkv_opts_t const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(16), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_open(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_open _cffi_d_fastkv_open
#endif

static fastkv_err_t _cffi_d_fastkv_put(fastkv_db_t * x0, fastkv_slice_t x1, fastkv_slice_t x2)
{
  return fastkv_put(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_put(PyObject *self, PyObject *args)
{
  fastkv_db_t * x0;
  fastkv_slice_t x1;
  fastkv_slice_t x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "fastkv_put", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(12), arg1) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x2, _cffi_type(12), arg2) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_put(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static fastkv_err_t _cffi_f_fastkv_put(fastkv_db_t * x0, fastkv_slice_t *x1, fastkv_slice_t *x2)
{
  fastkv_err_t result;
  { result = fastkv_put(x0, *x1, *x2); }
  return result;
}
#endif

static fastkv_err_t _cffi_d_fastkv_put_ttl(fastkv_db_t * x0, fastkv_slice_t x1, fastkv_slice_t x2, uint64_t x3)
{
  return fastkv_put_ttl(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_put_ttl(PyObject *self, PyObject *args)
{
  fastkv_db_t * x0;
  fastkv_slice_t x1;
  fastkv_slice_t x2;
  uint64_t x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "fastkv_put_ttl", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(12), arg1) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x2, _cffi_type(12), arg2) < 0)
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint64_t);
  if (x3 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_put_ttl(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static fastkv_err_t _cffi_f_fastkv_put_ttl(fastkv_db_t * x0, fastkv_slice_t *x1, fastkv_slice_t *x2, uint64_t x3)
{
  fastkv_err_t result;
  { result = fastkv_put_ttl(x0, *x1, *x2, x3); }
  return result;
}
#endif

static fastkv_err_t _cffi_d_fastkv_stats(fastkv_db_t * x0, fastkv_stats_t * x1)
{
  return fastkv_stats(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_stats(PyObject *self, PyObject *args)
{
  fastkv_db_t * x0;
  fastkv_stats_t * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "fastkv_stats", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(65), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (fastkv_stats_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(65), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_stats(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_stats _cffi_d_fastkv_stats
#endif

static char const * _cffi_d_fastkv_strerror(fastkv_err_t x0)
{
  return fastkv_strerror(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_strerror(PyObject *self, PyObject *arg0)
{
  fastkv_err_t x0;
  char const * result;
  PyObject *pyresult;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_strerror(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(28));
  return pyresult;
}
#else
#  define _cffi_f_fastkv_strerror _cffi_d_fastkv_strerror
#endif

static fastkv_err_t _cffi_d_fastkv_sync(fastkv_db_t * x0)
{
  return fastkv_sync(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_sync(PyObject *self, PyObject *arg0)
{
  fastkv_db_t * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_sync(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_sync _cffi_d_fastkv_sync
#endif

static fastkv_err_t _cffi_d_fastkv_txn_abort(fastkv_txn_t * x0)
{
  return fastkv_txn_abort(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_txn_abort(PyObject *self, PyObject *arg0)
{
  fastkv_txn_t * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(85), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_txn_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(85), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_txn_abort(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_txn_abort _cffi_d_fastkv_txn_abort
#endif

static fastkv_err_t _cffi_d_fastkv_txn_begin(fastkv_db_t * x0, _Bool x1, fastkv_txn_t * * x2)
{
  return fastkv_txn_begin(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_txn_begin(PyObject *self, PyObject *args)
{
  fastkv_db_t * x0;
  _Bool x1;
  fastkv_txn_t * * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "fastkv_txn_begin", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_db_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = (_Bool)_cffi_to_c__Bool(arg1);
  if (x1 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(24), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (fastkv_txn_t * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(24), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_txn_begin(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_txn_begin _cffi_d_fastkv_txn_begin
#endif

static fastkv_err_t _cffi_d_fastkv_txn_commit(fastkv_txn_t * x0)
{
  return fastkv_txn_commit(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_txn_commit(PyObject *self, PyObject *arg0)
{
  fastkv_txn_t * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(85), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_txn_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(85), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_txn_commit(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fastkv_txn_commit _cffi_d_fastkv_txn_commit
#endif

static fastkv_err_t _cffi_d_fastkv_txn_delete(fastkv_txn_t * x0, fastkv_slice_t x1)
{
  return fastkv_txn_delete(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_txn_delete(PyObject *self, PyObject *args)
{
  fastkv_txn_t * x0;
  fastkv_slice_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "fastkv_txn_delete", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(85), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_txn_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(85), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(12), arg1) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_txn_delete(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static fastkv_err_t _cffi_f_fastkv_txn_delete(fastkv_txn_t * x0, fastkv_slice_t *x1)
{
  fastkv_err_t result;
  { result = fastkv_txn_delete(x0, *x1); }
  return result;
}
#endif

static fastkv_err_t _cffi_d_fastkv_txn_get(fastkv_txn_t * x0, fastkv_slice_t x1, fastkv_slice_t * x2)
{
  return fastkv_txn_get(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_txn_get(PyObject *self, PyObject *args)
{
  fastkv_txn_t * x0;
  fastkv_slice_t x1;
  fastkv_slice_t * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "fastkv_txn_get", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(85), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_txn_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(85), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(12), arg1) < 0)
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (fastkv_slice_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(8), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_txn_get(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static fastkv_err_t _cffi_f_fastkv_txn_get(fastkv_txn_t * x0, fastkv_slice_t *x1, fastkv_slice_t * x2)
{
  fastkv_err_t result;
  { result = fastkv_txn_get(x0, *x1, x2); }
  return result;
}
#endif

static fastkv_err_t _cffi_d_fastkv_txn_put(fastkv_txn_t * x0, fastkv_slice_t x1, fastkv_slice_t x2)
{
  return fastkv_txn_put(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fastkv_txn_put(PyObject *self, PyObject *args)
{
  fastkv_txn_t * x0;
  fastkv_slice_t x1;
  fastkv_slice_t x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  fastkv_err_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "fastkv_txn_put", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(85), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (fastkv_txn_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(85), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(12), arg1) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x2, _cffi_type(12), arg2) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fastkv_txn_put(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
static fastkv_err_t _cffi_f_fastkv_txn_put(fastkv_txn_t * x0, fastkv_slice_t *x1, fastkv_slice_t *x2)
{
  fastkv_err_t result;
  { result = fastkv_txn_put(x0, *x1, *x2); }
  return result;
}
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "FASTKV_CURSOR_BACKWARD", (void *)_cffi_const_FASTKV_CURSOR_BACKWARD, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_CURSOR_FORWARD", (void *)_cffi_const_FASTKV_CURSOR_FORWARD, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_ERR_CORRUPT", (void *)_cffi_const_FASTKV_ERR_CORRUPT, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_ERR_CURSOR_EOF", (void *)_cffi_const_FASTKV_ERR_CURSOR_EOF, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_ERR_FULL", (void *)_cffi_const_FASTKV_ERR_FULL, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_ERR_INVAL", (void *)_cffi_const_FASTKV_ERR_INVAL, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_ERR_IO", (void *)_cffi_const_FASTKV_ERR_IO, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_ERR_KEYSIZE", (void *)_cffi_const_FASTKV_ERR_KEYSIZE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_ERR_NOMEM", (void *)_cffi_const_FASTKV_ERR_NOMEM, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_ERR_NOTFOUND", (void *)_cffi_const_FASTKV_ERR_NOTFOUND, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_ERR_TXN_CLOSED", (void *)_cffi_const_FASTKV_ERR_TXN_CLOSED, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_ERR_TXN_CONFLICT", (void *)_cffi_const_FASTKV_ERR_TXN_CONFLICT, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_ERR_TXN_RO", (void *)_cffi_const_FASTKV_ERR_TXN_RO, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_ERR_VALSIZE", (void *)_cffi_const_FASTKV_ERR_VALSIZE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FASTKV_OK", (void *)_cffi_const_FASTKV_OK, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "fastkv_close", (void *)_cffi_f_fastkv_close, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 18), (void *)_cffi_d_fastkv_close },
  { "fastkv_cursor_close", (void *)_cffi_f_fastkv_cursor_close, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 115), (void *)_cffi_d_fastkv_cursor_close },
  { "fastkv_cursor_key", (void *)_cffi_f_fastkv_cursor_key, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 6), (void *)_cffi_d_fastkv_cursor_key },
  { "fastkv_cursor_next", (void *)_cffi_f_fastkv_cursor_next, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 3), (void *)_cffi_d_fastkv_cursor_next },
  { "fastkv_cursor_open", (void *)_cffi_f_fastkv_cursor_open, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 87), (void *)_cffi_d_fastkv_cursor_open },
  { "fastkv_cursor_seek", (void *)_cffi_f_fastkv_cursor_seek, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 10), (void *)_cffi_d_fastkv_cursor_seek },
  { "fastkv_cursor_value", (void *)_cffi_f_fastkv_cursor_value, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 6), (void *)_cffi_d_fastkv_cursor_value },
  { "fastkv_delete", (void *)_cffi_f_fastkv_delete, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 43), (void *)_cffi_d_fastkv_delete },
  { "fastkv_free_value", (void *)_cffi_f_fastkv_free_value, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 118), (void *)_cffi_d_fastkv_free_value },
  { "fastkv_get", (void *)_cffi_f_fastkv_get, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 47), (void *)_cffi_d_fastkv_get },
  { "fastkv_index_create", (void *)_cffi_f_fastkv_index_create, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 36), (void *)_cffi_d_fastkv_index_create },
  { "fastkv_index_drop", (void *)_cffi_f_fastkv_index_drop, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 26), (void *)_cffi_d_fastkv_index_drop },
  { "fastkv_index_lookup", (void *)_cffi_f_fastkv_index_lookup, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 67), (void *)_cffi_d_fastkv_index_lookup },
  { "fastkv_index_range", (void *)_cffi_f_fastkv_index_range, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 73), (void *)_cffi_d_fastkv_index_range },
  { "fastkv_json_index_create", (void *)_cffi_f_fastkv_json_index_create, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 30), (void *)_cffi_d_fastkv_json_index_create },
  { "fastkv_open", (void *)_cffi_f_fastkv_open, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 14), (void *)_cffi_d_fastkv_open },
  { "fastkv_put", (void *)_cffi_f_fastkv_put, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 52), (void *)_cffi_d_fastkv_put },
  { "fastkv_put_ttl", (void *)_cffi_f_fastkv_put_ttl, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 57), (void *)_cffi_d_fastkv_put_ttl },
  { "fastkv_stats", (void *)_cffi_f_fastkv_stats, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 63), (void *)_cffi_d_fastkv_stats },
  { "fastkv_strerror", (void *)_cffi_f_fastkv_strerror, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 0), (void *)_cffi_d_fastkv_strerror },
  { "fastkv_sync", (void *)_cffi_f_fastkv_sync, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 18), (void *)_cffi_d_fastkv_sync },
  { "fastkv_txn_abort", (void *)_cffi_f_fastkv_txn_abort, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 84), (void *)_cffi_d_fastkv_txn_abort },
  { "fastkv_txn_begin", (void *)_cffi_f_fastkv_txn_begin, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 21), (void *)_cffi_d_fastkv_txn_begin },
  { "fastkv_txn_commit", (void *)_cffi_f_fastkv_txn_commit, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 84), (void *)_cffi_d_fastkv_txn_commit },
  { "fastkv_txn_delete", (void *)_cffi_f_fastkv_txn_delete, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 92), (void *)_cffi_d_fastkv_txn_delete },
  { "fastkv_txn_get", (void *)_cffi_f_fastkv_txn_get, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 96), (void *)_cffi_d_fastkv_txn_get },
  { "fastkv_txn_put", (void *)_cffi_f_fastkv_txn_put, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 101), (void *)_cffi_d_fastkv_txn_put },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "path", offsetof(fastkv_opts_t, path),
            sizeof(((fastkv_opts_t *)0)->path),
            _CFFI_OP(_CFFI_OP_NOOP, 28) },
  { "map_size", offsetof(fastkv_opts_t, map_size),
                sizeof(((fastkv_opts_t *)0)->map_size),
                _CFFI_OP(_CFFI_OP_NOOP, 113) },
  { "arena_size", offsetof(fastkv_opts_t, arena_size),
                  sizeof(((fastkv_opts_t *)0)->arena_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 113) },
  { "sync_writes", offsetof(fastkv_opts_t, sync_writes),
                   sizeof(((fastkv_opts_t *)0)->sync_writes),
                   _CFFI_OP(_CFFI_OP_NOOP, 23) },
  { "read_only", offsetof(fastkv_opts_t, read_only),
                 sizeof(((fastkv_opts_t *)0)->read_only),
                 _CFFI_OP(_CFFI_OP_NOOP, 23) },
  { "malloc_fn", offsetof(fastkv_opts_t, malloc_fn),
                 sizeof(((fastkv_opts_t *)0)->malloc_fn),
                 _CFFI_OP(_CFFI_OP_NOOP, 135) },
  { "free_fn", offsetof(fastkv_opts_t, free_fn),
               sizeof(((fastkv_opts_t *)0)->free_fn),
               _CFFI_OP(_CFFI_OP_NOOP, 136) },
  { "data", offsetof(fastkv_slice_t, data),
            sizeof(((fastkv_slice_t *)0)->data),
            _CFFI_OP(_CFFI_OP_NOOP, 133) },
  { "len", offsetof(fastkv_slice_t, len),
           sizeof(((fastkv_slice_t *)0)->len),
           _CFFI_OP(_CFFI_OP_NOOP, 113) },
  { "num_keys", offsetof(fastkv_stats_t, num_keys),
                sizeof(((fastkv_stats_t *)0)->num_keys),
                _CFFI_OP(_CFFI_OP_NOOP, 61) },
  { "num_txn_committed", offsetof(fastkv_stats_t, num_txn_committed),
                         sizeof(((fastkv_stats_t *)0)->num_txn_committed),
                         _CFFI_OP(_CFFI_OP_NOOP, 61) },
  { "num_txn_aborted", offsetof(fastkv_stats_t, num_txn_aborted),
                       sizeof(((fastkv_stats_t *)0)->num_txn_aborted),
                       _CFFI_OP(_CFFI_OP_NOOP, 61) },
  { "num_txn_conflicts", offsetof(fastkv_stats_t, num_txn_conflicts),
                         sizeof(((fastkv_stats_t *)0)->num_txn_conflicts),
                         _CFFI_OP(_CFFI_OP_NOOP, 61) },
  { "wal_bytes_written", offsetof(fastkv_stats_t, wal_bytes_written),
                         sizeof(((fastkv_stats_t *)0)->wal_bytes_written),
                         _CFFI_OP(_CFFI_OP_NOOP, 61) },
  { "snapshot_count", offsetof(fastkv_stats_t, snapshot_count),
                      sizeof(((fastkv_stats_t *)0)->snapshot_count),
                      _CFFI_OP(_CFFI_OP_NOOP, 61) },
  { "arena_alloc_bytes", offsetof(fastkv_stats_t, arena_alloc_bytes),
                         sizeof(((fastkv_stats_t *)0)->arena_alloc_bytes),
                         _CFFI_OP(_CFFI_OP_NOOP, 61) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$fastkv_opts_t", 129, _CFFI_F_CHECK_FIELDS,
    sizeof(fastkv_opts_t), offsetof(struct _cffi_align_typedef_fastkv_opts_t, y), 0, 7 },
  { "$fastkv_slice_t", 12, _CFFI_F_CHECK_FIELDS,
    sizeof(fastkv_slice_t), offsetof(struct _cffi_align_typedef_fastkv_slice_t, y), 7, 2 },
  { "$fastkv_stats_t", 130, _CFFI_F_CHECK_FIELDS,
    sizeof(fastkv_stats_t), offsetof(struct _cffi_align_typedef_fastkv_stats_t, y), 9, 7 },
  { "fastkv_cursor", 126, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "fastkv_db", 127, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "fastkv_index", 128, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "fastkv_txn", 131, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$fastkv_cursor_dir_t", 89, _cffi_prim_int(sizeof(fastkv_cursor_dir_t), ((fastkv_cursor_dir_t)-1) <= 0),
    "FASTKV_CURSOR_FORWARD,FASTKV_CURSOR_BACKWARD" },
  { "$fastkv_err_t", 1, _cffi_prim_int(sizeof(fastkv_err_t), ((fastkv_err_t)-1) <= 0),
    "FASTKV_OK,FASTKV_ERR_NOMEM,FASTKV_ERR_INVAL,FASTKV_ERR_IO,FASTKV_ERR_CORRUPT,FASTKV_ERR_FULL,FASTKV_ERR_NOTFOUND,FASTKV_ERR_KEYSIZE,FASTKV_ERR_VALSIZE,FASTKV_ERR_TXN_RO,FASTKV_ERR_TXN_CONFLICT,FASTKV_ERR_TXN_CLOSED,FASTKV_ERR_CURSOR_EOF" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "fastkv_cursor_dir_t", 89 },
  { "fastkv_cursor_t", 126 },
  { "fastkv_db_t", 127 },
  { "fastkv_err_t", 1 },
  { "fastkv_index_fn", 39 },
  { "fastkv_index_scan_cb", 70 },
  { "fastkv_index_t", 128 },
  { "fastkv_opts_t", 129 },
  { "fastkv_slice_t", 12 },
  { "fastkv_stats_t", 130 },
  { "fastkv_txn_t", 131 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  42,  /* num_globals */
  7,  /* num_struct_unions */
  2,  /* num_enums */
  11,  /* num_typenames */
  NULL,  /* no includes */
  138,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__libfastkv(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit__libfastkv(void) { return NULL; }
#  else
     init_libfastkv(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit__libfastkv(void)
{
  return _cffi_init("fastkv._libfastkv", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
init_libfastkv(void)
{
  _cffi_init("fastkv._libfastkv", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
